### ISSUE TITLE
App crashes when inputting text in entry selection step

### ISSUE THREAD

**Issue by AdanAlonso** [Usabi/bcup-cli#11]
In the `Select entry to copy or enter for search again:` step, if text is inputted, the app crashes.

Also, if there are no results, it also returns to this step, instead of just letting the user search again directly.

```
Search text in folder or title. You can use RegExp: something
0 exit


Select entry to copy or enter for search again: text
(node:187193) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getProperty' of undefined
    at fileDatasource.load.then.then.vault (/usr/local/lib/node_modules/bcup-cli/src/cli.ts:59:41)
(node:187193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:187193) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ialiendeg** [comment]
Fixed all possible crashes... I hope :)

> Also, if there are no results, it also returns to this step, instead of just letting the user search again directly.
> 
> ```
> Search text in folder or title. You can use RegExp: something
> 0 exit
> 

That not changed, needs refactoring and it's only a click in enter :)
